# -*- coding: utf-8 -*-
"""module 9 assignment 3 (1).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nsfsWfA9_bv-IFmuUt3h5proN5DxbXm6
"""

from sklearn.datasets import load_iris

iris=load_iris()

iris

x=iris.data

x

from sklearn.cluster import AgglomerativeClustering

cluster=AgglomerativeClustering(n_clusters=3,affinity='euclidean',linkage='ward')

cluster.fit_predict(x)

# Commented out IPython magic to ensure Python compatibility.
import scipy.cluster.hierarchy as sch
import matplotlib.pyplot as plt
# %matplotlib inline
plt.figure(figsize=(10,7))
plt.title("dendrogram")
dend=sch.dendrogram(sch.linkage(x,method='ward'))
plt.axhline(y=15,color='red',linestyle='--',linewidth=3)

